// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	UserID    uuid.UUID
	Content   string
	CreatedAt time.Time
}

type CommentVote struct {
	CommentID uuid.UUID
	UserID    uuid.UUID
	Kind      string
}

type Post struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Content   string
	Answered  bool
	CreatedAt time.Time
}

type PostAnswer struct {
	PostID    uuid.UUID
	CommentID uuid.UUID
}

type PostTag struct {
	PostID uuid.UUID
	TagID  int32
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Tag struct {
	ID        int32
	Name      string
	CreatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	Name           string
	Bio            sql.NullString
	Username       string
	HashedPassword string
	CreatedAt      time.Time
}
